INSERT INTO users(name, age) VALUES ("Chris", 10);
INSERT INTO users(name, age) VALUES ("Mike", 11);
INSERT INTO users(name, age) VALUES ("Sean", 12);
INSERT INTO users(name, age) VALUES ("Sal", 13);
INSERT INTO users(name, age) VALUES ("Sally", 14);
INSERT INTO users(name, age) VALUES ("Joe", 15);
INSERT INTO users(name, age) VALUES ("Alex", 15);
INSERT INTO users(name, age) VALUES ("Frank", 16);
INSERT INTO users(name, age) VALUES ("Bob", 17);
INSERT INTO users(name, age) VALUES ("Tristan", 18);
INSERT INTO users(name, age) VALUES ("Forrest", 19);
INSERT INTO users(name, age) VALUES ("Abhi", 20);
INSERT INTO users(name, age) VALUES ("Tyler", 21);
INSERT INTO users(name, age) VALUES ("A", 22);
INSERT INTO users(name, age) VALUES ("B", 23);
INSERT INTO users(name, age) VALUES ("C", 1);
INSERT INTO users(name, age) VALUES ("D", 2);
INSERT INTO users(name, age) VALUES ("E", 3);
INSERT INTO users(name, age) VALUES ("F", 4);
INSERT INTO users(name, age) VALUES ("G", 5);

INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 1", "Enviroment", 10000, "01/1/20", "01/1/21");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 2", "Health", 20000, "02/2/20", "02/2/23");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 3", "Pets", 15000, "03/3/20", "03/3/23");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 4", "Gaming", 34400, "04/4/20", "04/4/26");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 5", "Politics", 545570, "05/5/20", "05/5/27");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 6", "Music", 23445, "06/6/20", "06/6/29");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 7", "Stocks", 35543, "07/7/20", "07/7/28");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 8", "Gaming", 354505, "08/8/20", "08/8/24");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 9", "Race Cars", 32452, "09/9/20", "09/9/24");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("Start Up 10", "Nature", 352235, "10/10/20", "10/10/22");

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);